name: productpage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: checkout code
    
#     - name: Docker build
#     - uses: docker/setup-buildx-action@v1    
      
      - name: Login to github registry
        uses: docker/login-action@v1 
        with:
         username: ${{ github.repository_owner }}
         password: ${{ secrets.TOKEN_GITHUB__BP }}
        
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/Pungpeee/bookinfo-productpage
        
  deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Execute ssh command to remote server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: Pungpeee
            password: ${{ secrets.PASSWORD }}
            scripts: |
               docker pull ghcr.io/Pungpeee/bookinfo-productpage
               docker build -t ghcr.io/Pungpeee/bookinfo-productpage
               docker images
               docker ps -a
               
    
    
